### ISSUE TITLE
Base signature should also contain request body

### ISSUE THREAD

**Issue by sebastianhoitz** [gremo/GremoHmacAuthenticationBundle#1]
You should expand the HmacAuthenticationProvider so that it can also contain the request body. Or otherwise provider better adjustment possibility.

What I did is that I basically copied the `HmacAuthenticationProvider` class to my project and then adjusted the `buildCanonicalStringFromRequest` method.

I could not just extend from your class because all the methods are private. Would it make sense to adjust them to be protected?

**Comment by gremo** [comment]
Can you please make a PR with the suggested changes? Thanks!

**Comment by gremo** [comment]
Which changes you suggest? Give me some idea I can work on, thanks!

**Comment by Ronnie-J** [comment]
@gremo isen't this mitigated by the fact that you can use the `Content-MD5` header? Then the body can't be manipulated.

**Comment by gremo** [comment]
@Ronnie-J sure you're right. If you put the Content-MD5 header in the verify-headers it will be checked too. That is, body cannot be altered without changing the signature too.
