### ISSUE TITLE
The roles are not in the token

### ISSUE THREAD

**Issue by mirandaguillaume** [gremo/GremoHmacAuthenticationBundle#3]
I wanted to use roles with your bundle and I came unto an issue. The roles are not setted to the token and the Symfony Security can't check them because he's also trying to reauthenticate the HMAC token, which does not have the authenticated boolean setted to true or the signature in it.

Thank in advance for your anwser.

**Comment by gremo** [comment]
Hi! Prease provide a code sample so I can dig into this issue. Thanks for collaborating

**Comment by mirandaguillaume** [comment]
If I try to add a $this->denyAccessUnlessGranted('ROLE_USER'); to the controller it throws an exception because the HMAC token sent by the HMACAuthorizationProvider doesn't have the signature and/or the Authenticated attribute isn't set to true.
Then it still fails, but without an exception, this time because the token require the roles to be set in the constructor.

Hope this will help

**Comment by gremo** [comment]
Thanks @mirandaguillaume . I look into this during this week and solve it.

**Comment by mirandaguillaume** [comment]
Thanks a lot !
