### ISSUE TITLE
Support Symfony 5

### ISSUE THREAD

**Issue by RonSchofield** [gremo/GremoHmacAuthenticationBundle#6]
Make sure that this works with Symfony 5.

**Comment by gremo** [comment]
Have you a PR?

**Comment by RonSchofield** [comment]
No. I am currently learning Symfony coming from Laravel and don't know enough to create one. I want to use HMAC and I your package is the only one that I have found that works with any version of Symfony. I don't know what has changed from 4 to 5 that would need to be changed.

**Comment by tarlepp** [comment]
Also I think it's time to drop support for those Symfony versions that aren't anymore supported - https://symfony.com/releases

Currently this bundle is using; `"~2.3|~3.0|~4.0"`, so I would drop those not supported versions there...

And for that

> I don't know what has changed from 4 to 5 that would need to be changed.

It would really help if there was some test cases to cover different Symfony versions, so that people could make changes like this.

**Comment by gremo** [comment]
@RonSchofield that's funny, I'm trying to doing the opposite (leaving Symfony for Laravel) 😄 Right now, I'm not using this bundle actively, I'm trying to move forward the Nodejs world.

Anyways I agree with @tarlepp but, maybe, BC compatibility could be accomplished with a few lines of code. Do not have so much time to study this ATM. @tarlepp are you able to provide a PR?

**Comment by tarlepp** [comment]
Sorry I don't use this bundle - I just advice someone to rise issue about lacking support of SF5 to this bundle - and just looked this repository after that and noticed that this bundle is supporting not maintained SF versions.

So what I would do first is to change
```
        "symfony/framework-bundle": "~2.3|~3.0|~4.0",
        "symfony/security-bundle": "~2.3|~3.0|~4.0",
        "symfony/polyfill-php56": "~1.0"
```
to
```
        "symfony/framework-bundle": "~3.4|~4.4",
        "symfony/security-bundle": "~3.4|~4.4",
        "symfony/polyfill": "~1.0"
```

After that I would use eg. TravisCI to test this bundle with those Symfony versions - this would need some actual test writing.

And after this all, I would add that SF5 support to `composer.json` and change your TravisCI configuration also cover that Symfony version.

And if this all is too much someone could just fork this repository, and make that one only to support SF5 - and really mention that the main work for this was done in _this_ repository.
